maintainer       "Doug MacEachern"
maintainer_email "dougm@vmware.com"
license          "VMware internal"
description      "Installs and configures Cloud2Code Hudson Slaves"
version          "0.1"
depends          "cfc"
depends          "openssh"
depends          "maven"
depends "etchosts"
