maintainer       "Clint Morgan"
maintainer_email "clint.morgan@tasktop.com"
license          "EPL"
description      "Installs and configures Code2Cloud Nexus server"
version          "0.1"
depends "c2c_server"
depends          "nexus"
