maintainer       "Clint Morgan"
maintainer_email "clint.morgan@tasktop.com"
license          "EPL"
description      "Installs and configures Code2Cloud Hudson Slaves"
version          "0.1"
depends          "c2c"
depends          "openssh"
depends          "maven"
depends "etchosts"
