default[:ant][:url] = "http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.0-bin.tar.gz"
default[:ant][:install_dir] = "apache-ant-1.9.0"
default[:ant][:package] = "apache-ant-1.9.0-bin.tar.gz"
default[:ant][:root_dir] = "/usr/local/ant"
default[:ant][:bin] = "/usr/local/bin/ant"
