maintainer       "Doug MacEachern"
maintainer_email "dougm@vmware.com"
license          "VMware internal"
description      "Installs and configures Cloud2Code DB"
version          "0.1"
depends          "cfc"
depends          "mysql"
