maintainer       "Clint Morgan"
maintainer_email "clint.morgan@tasktop.com"
license          "EPL"
description      "Installs and configures Code2Cloud DB"
version          "0.1"
depends          "cfc"
depends          "mysql"
